### ISSUE TITLE
Передача команд в массиве mgs.payload

### ISSUE THREAD

**Issue by v-bondarev** [n0name45/node-red-contrib-yandex-station-management#10]
Колонка: Яндекс.Мини первого поколения.

Если передавать через function одну команду, то отрабатывает успешно. Если же попробовать передать команды в массиве:

msg.payload = [
{ "command": "stop" }.
"command": "start" }
]

То они не отрабатывают. В дебаг приходит массив.

**Comment by n0name45** [comment]
добрый день! отправляется все в raw-режиме? Работает на примере по нескольким командам из документации?

**Comment by v-bondarev** [comment]
Добрый день,

Отправляется в RAW, одна команда отрабатывает отлично. А вот если сделать массив как в документации, то в дебаг-ноду приходить правильно как массив, а вот колонка молчит.

**Comment by n0name45** [comment]
> Добрый день, Отправляется в RAW, одна команда отрабатывает отлично. А вот если сделать массив как в документации, то в дебаг-ноду приходить правильно как массив, а вот колонка молчит.
> […](#)
> 5 нояб. 2021 г., в 21:09, n0name ***@***.***> написал(а): ﻿ добрый день! отправляется все в raw-режиме? Работает на примере по нескольким командам из документации? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

добрый день!

Проверил массив из [документации](https://github.com/n0name45/node-red-contrib-yandex-station-management#пример-использования-нескольких-raw-команд) на первой мини- все работает.

Убедитесь, что на вход raw-ноде отправляется именно объект, а не строка.
Убедитесь, что объект корректный - у вас в примере ошибка в JSON:
 msg.payload = [
{ "command": "stop" },
{"command": "start" }
]
Если все это не сработает, то нужны скриншоты или кусок вашего кода для импорта.
