### ISSUE TITLE
Перезагрузка NR

### ISSUE THREAD

**Issue by sanyafifa** [n0name45/node-red-contrib-yandex-station-management#14]
Несколько раз в день ловлю в логах такое:

`Dec 06 16:46:57 raspberrypi Node-RED[7310]: 6 Dec 16:46:57 - [error] TypeError: Cannot read property 'readyState' of undefined
Dec 06 16:46:57 raspberrypi Node-RED[7310]:     at WebSocket.close (/home/pi/.node-red/node_modules/node-red-contrib-yandex-station-management/nodes/yandex-login.js:326
Dec 06 16:46:57 raspberrypi Node-RED[7310]:     at WebSocket.emit (events.js:400:28)
Dec 06 16:46:57 raspberrypi Node-RED[7310]:     at WebSocket.emitClose (/home/pi/.node-red/node_modules/ws/lib/websocket.js:246:10)
Dec 06 16:46:57 raspberrypi Node-RED[7310]:     at TLSSocket.socketOnClose (/home/pi/.node-red/node_modules/ws/lib/websocket.js:1063:15)
Dec 06 16:46:57 raspberrypi Node-RED[7310]:     at TLSSocket.emit (events.js:412:35)
Dec 06 16:46:57 raspberrypi Node-RED[7310]:     at net.js:686:12
Dec 06 16:46:57 raspberrypi Node-RED[7310]:     at TCP.done (_tls_wrap.js:564:7)
Dec 06 16:46:58 raspberrypi systemd[1]: nodered.service: Main process exited, code=exited, status=1/FAILURE
Dec 06 16:46:58 raspberrypi systemd[1]: nodered.service: Failed with result 'exit-code'.
Dec 06 16:47:18 raspberrypi systemd[1]: nodered.service: Service RestartSec=20s expired, scheduling restart.
Dec 06 16:47:18 raspberrypi systemd[1]: nodered.service: Scheduled restart job, restart counter is at 2.
Dec 06 16:47:18 raspberrypi systemd[1]: Stopped Node-RED graphical event wiring tool.
Dec 06 16:47:18 raspberrypi systemd[1]: Started Node-RED graphical event wiring tool.
Dec 06 16:47:19 raspberrypi Node-RED[7813]: 6 Dec 16:47:19 - [info]
Dec 06 16:47:19 raspberrypi Node-RED[7813]: Welcome to Node-RED
Dec 06 16:47:19 raspberrypi Node-RED[7813]: ===================

`

по моим наблюдениям ошибка появляется  когда инет пропадает

`[info] Node-RED version: v2.1.4
[info] Node.js  version: v14.18.2
 [info] Linux 5.10.63-v7l+ arm LE`

**Comment by n0name45** [comment]
+ node-red-contrib-yandex-station-management@0.3.2
