### ISSUE TITLE
Не находится колонка. 

### ISSUE THREAD

**Issue by pistoletov1974** [n0name45/node-red-contrib-yandex-station-management#23]
Спасибо большое за Вашу работу. Пытаюсь подключится к колонке через Токен. Токен от Яндекс музыки получил. 
В логах вижу ошибки:
8 May 11:25:25 - [info] [yandex-login:loft] Starting server with id d157a59f52db894c
8 May 11:25:25 - [info] [alice-local-out:53a431c2f9e15303] undefined
8 May 11:25:25 - [info] [alice-local-out:53a431c2f9e15303] Status: {"color":"red","text":"disconnected"}
8 May 11:25:25 - [info] Started flows
Catching error on address already in use: {"errno":-98,"code":"EADDRINUSE","syscall":"addMembership"}
Catching error on dropMembership: {"errno":-99,"code":"EADDRNOTAVAIL","syscall":"dropMembership"}

**Comment by n0name45** [comment]
> Проблему понял. У меня сервер node-red и колонка находятся в разных подсетях. а TTS локально генерируется или через облако?

Добрый день! ТТС генерируется в облаке. Если отключить интернет, то без серверов яндекса ничего работать не будет
