### ISSUE TITLE
Не отображается в списке Станций - Станция Макс

### ISSUE THREAD

**Issue by FurmanenkoIgor** [n0name45/node-red-contrib-yandex-station-management#3]
После нажатия ![image](https://user-images.githubusercontent.com/81693923/116739211-1559ee00-a9fc-11eb-86c5-3636f510fa93.png) станция появляется в списке.
![image](https://user-images.githubusercontent.com/81693923/116739294-2acf1800-a9fc-11eb-94a2-dcaa1082b890.png)
Но после сохранения настроек, станция пропадает из списка. Возможно это из-за шаблона серийного номера 
![image](https://user-images.githubusercontent.com/81693923/116739401-4d613100-a9fc-11eb-84ff-fe4641347875.png)

**Comment by n0name45** [comment]
> После нажатия ![image](https://user-images.githubusercontent.com/81693923/116739211-1559ee00-a9fc-11eb-86c5-3636f510fa93.png) станция появляется в списке.
> ![image](https://user-images.githubusercontent.com/81693923/116739294-2acf1800-a9fc-11eb-94a2-dcaa1082b890.png)
> Но после сохранения настроек, станция пропадает из списка. Возможно это из-за шаблона серийного номера
> ![image](https://user-images.githubusercontent.com/81693923/116739401-4d613100-a9fc-11eb-84ff-fe4641347875.png)

а в какой ноде(station, in, out, get) жмете кнопки?

**Comment by FurmanenkoIgor** [comment]
Работало с самого начала только в station. Но спустя несколько дней решил вернуться к вопросу и проверить еще раз. Станция зафиксировалась в выпадающем списке во всех остальных блоках. Больше пока не исчезает. Не знаю почему понадобилось столь значительное время.
